server:
  port: 8080

spring:
  config:
    activate:
      on-profile: dev
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

logstream:
  channels: server-channel,system-channel,app1-channel,app2-channel,app3-channel,app4-channel
  allowed-origins: http://localhost:5173
  log-dir: # set to local log directory if testing file download
  max-sessions-per-user: 5
  replay-buffer-size: 500
